name: tine20drive CI

on: [push]


jobs:
# ------------------------------------------------------------------------------------------------------------------------------------------
  build:
    name: Build tine20drive
    runs-on: ubuntu-latest
    container:
      image: nextcloudci/client-5.12:client-5.12-9

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |

        set -xe
        ls -al
        mkdir /app

        #Set Qt-5.12
        export QT_BASE_DIR=/opt/qt5.12.9
        export QTDIR=$QT_BASE_DIR
        export PATH=$QT_BASE_DIR/bin:$PATH
        export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

        #Set APPID for .desktop file processing
        export LINUX_APPLICATION_ID=com.tine20.desktopclient.tine20drive

        #set defaults
        export SUFFIX="master"

        #QtKeyChain master

        git clone https://github.com/frankosterfeld/qtkeychain.git
        cd qtkeychain
        git checkout master
        mkdir build
        cd build
        cmake -D CMAKE_INSTALL_PREFIX=/usr ../
        make -j4
        make DESTDIR=/app install 

        cd ../..

        #Build client

        mkdir build-client
        cd build-client

        cmake -D CMAKE_INSTALL_PREFIX=/usr \
        -D NO_SHIBBOLETH=1 \
        -D BUILD_UPDATER=ON \
        -D QTKEYCHAIN_LIBRARY=/app/usr/lib/x86_64-linux-gnu/libqt5keychain.so \
        -D QTKEYCHAIN_INCLUDE_DIR=/app/usr/include/qt5keychain/ \
        -DMIRALL_VERSION_SUFFIX=master \
        -DMIRALL_VERSION_BUILD=$GITHUB_RUN_NUMBER \
        $GITHUB_WORKSPACE

        make -j4
        make DESTDIR=/app install

        # Move stuff around
        cd /app

        mv ./usr/lib/x86_64-linux-gnu/tine20drive/* ./usr/lib/x86_64-linux-gnu/
        mv ./usr/lib/x86_64-linux-gnu/* ./usr/lib/
        rm -rf ./usr/lib/tine20drive
        rm -rf ./usr/lib/cmake
        rm -rf ./usr/include
        rm -rf ./usr/mkspecs
        rm -rf ./usr/lib/x86_64-linux-gnu/

        # Don't bundle nextcloudcmd as we don't run it anyway
        rm -rf ./usr/bin/tine20drivecmd

        # Don't bundle the explorer extentions as we can't do anything with them in the AppImage
        rm -rf ./usr/share/caja-python/
        rm -rf ./usr/share/nautilus-python/
        rm -rf ./usr/share/nemo-python/

        # Move sync exclude to right location
        mv ./etc/tine20drive/sync-exclude.lst ./usr/bin/
        rm -rf ./etc

        DESKTOP_FILE=/app/usr/share/applications/${LINUX_APPLICATION_ID}.desktop
        sed -i -e 's|Icon=tine20drive|Icon=tine20drive|g' ${DESKTOP_FILE} # Bug in desktop file?
        cp ./usr/share/icons/hicolor/512x512/apps/tine20drive.png . # Workaround for linuxeployqt bug, FIXME


        # Because distros need to get their shit together
        cp -R /lib/x86_64-linux-gnu/libssl.so* ./usr/lib/
        cp -R /lib/x86_64-linux-gnu/libcrypto.so* ./usr/lib/
        cp -P /usr/local/lib/libssl.so* ./usr/lib/
        cp -P /usr/local/lib/libcrypto.so* ./usr/lib/

        # NSS fun
        cp -P -r /usr/lib/x86_64-linux-gnu/nss ./usr/lib/

        # Use linuxdeployqt to deploy
        cd 
        wget --ca-directory=/etc/ssl/certs/ -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt*.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
        rm ./linuxdeployqt-continuous-x86_64.AppImage
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=/app/usr/lib/
        ./squashfs-root/AppRun ${DESKTOP_FILE} -bundle-non-qt-libs -qmldir=$GITHUB_WORKSPACE/src/gui

        # Set origin
        ./squashfs-root/usr/bin/patchelf --set-rpath '$ORIGIN/' /app/usr/lib/libtine20drivesync.so.0

        # Build AppImage
        ./squashfs-root/AppRun ${DESKTOP_FILE} -appimage

        mv Tine_2.0_Drive*.AppImage Tine_2.0_Drive-${SUFFIX}-${GITHUB_RUN_NUMBER}-x86_64.AppImage

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: tine20drive
        path: /home/runner/work/_temp/_github_home/*.AppImage 

    - name: Make Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /home/runner/work/_temp/_github_home/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
